const restaurants = [
    {
      name: "Nhà Hàng Quán Ăn Ngon",
      seats: 80,
      image: "https://images.pexels.com/photos/4252136/pexels-photo-4252136.jpeg",
      address: "18 Phan Bội Châu, Quận Hoàn Kiếm, Hà Nội",
      opening: "09:00",
      closing: "22:00",
    },
    {
      name: "Cơm Niêu Sài Gòn",
      seats: 70,
      image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
      address: "59 Hồ Xuân Hương, Quận 3, TP. Hồ Chí Minh",
      opening: "10:00",
      closing: "22:30",
    },
    {
      name: "Nhà Hàng Gạo",
      seats: 100,
      image: "https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg",
      address: "33 Lê Quý Đôn, Quận 3, TP. Hồ Chí Minh",
      opening: "11:00",
      closing: "23:00",
    },
    {
      name: "Ẩm Thực Quê Nhà",
      seats: 85,
      image: "https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg",
      address: "86 Nguyễn Du, Quận Hai Bà Trưng, Hà Nội",
      opening: "10:30",
      closing: "22:00",
    },
    {
      name: "Nhà Hàng Sen Tây Hồ",
      seats: 200,
      image: "https://images.pexels.com/photos/262047/pexels-photo-262047.jpeg",
      address: "614 Lạc Long Quân, Quận Tây Hồ, Hà Nội",
      opening: "11:00",
      closing: "21:30",
    },
    {
      name: "Nhà Hàng Hương Sen",
      seats: 60,
      image: "https://images.pexels.com/photos/1537635/pexels-photo-1537635.jpeg",
      address: "52 Quang Trung, Quận Hải Châu, Đà Nẵng",
      opening: "10:00",
      closing: "22:00",
    },
    {
      name: "Bún Chả Hương Liên",
      seats: 45,
      image: "https://images.pexels.com/photos/616354/pexels-photo-616354.jpeg",
      address: "24 Lê Văn Hưu, Quận Hai Bà Trưng, Hà Nội",
      opening: "08:00",
      closing: "20:30",
    },
    {
      name: "Nhà Hàng Ngon Garden",
      seats: 90,
      image: "https://images.pexels.com/photos/262047/pexels-photo-262047.jpeg",
      address: "70 Nguyễn Du, Quận Hai Bà Trưng, Hà Nội",
      opening: "10:00",
      closing: "22:00",
    },
    {
      name: "Cơm Gà Hội An",
      seats: 55,
      image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
      address: "47 Phan Chu Trinh, Thành phố Hội An, Quảng Nam",
      opening: "09:30",
      closing: "21:00",
    },
    {
      name: "Nhà Hàng Biển Đông",
      seats: 100,
      image: "https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg",
      address: "2 Hoàng Sa, Quận Sơn Trà, Đà Nẵng",
      opening: "10:00",
      closing: "23:00",
    },
    {
      name: "Ẩm Thực Đồng Quê",
      seats: 75,
      image: "https://images.pexels.com/photos/6267/menu-restaurant-vintage-table.jpg",
      address: "120 Nguyễn Văn Cừ, Quận Long Biên, Hà Nội",
      opening: "09:00",
      closing: "21:30",
    },
    {
      name: "Nhà Hàng Tre Việt",
      seats: 95,
      image: "https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg",
      address: "60 Trần Phú, Quận Hà Đông, Hà Nội",
      opening: "10:30",
      closing: "22:30",
    },
    {
      name: "Quán Bụi",
      seats: 65,
      image: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg",
      address: "19 Ngô Văn Năm, Quận 1, TP. Hồ Chí Minh",
      opening: "11:00",
      closing: "22:00",
    },
  ];

  export default restaurants;